arch:
- aarch64
- amd64
- armhf
- armv7
- i386
description: TV streaming server and recorder.
image: ghcr.io/gauthamvarmak/tvheadend/{arch}
devices:
- /dev/dvb
- /dev/dri
map:
- config:rw
name: TVHeadend
ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
options:
  system_packages: []
  init_commands: []
schema:
  system_packages:
    - str
  init_commands:
    - str
slug: tvheadend
stage: experimental
url: https://github.com/Nachwahl/addon-tvheadend
version: 2.3.0
webui: http://[HOST]:[PORT:9981]/
host_network: true

